### ISSUE TITLE
Line break between URL and icon in visit newsroom link on listing detail header

### ISSUE THREAD

**Issue by tobek** [joincivil/Civil#1040]
On https://registry.civil.co/listing/0x954d3a15c27e65f70504a6c4f0ebad79cce5fa11 I assume this line break shouldn't be there:

![image](https://user-images.githubusercontent.com/3081073/53834664-a5ee2e00-3f59-11e9-8ca2-11943aec6911.png)

Should `&nbsp;` or `nowrap` or something but it needs to handle longer URLs too.

**Comment by tobek** [comment]
On second thought, although it looks a bit broken, maybe this is an edge case of the exact length where this can't be handled any other way? Except maybe something like absolutely positioning the arrow on the right edge of button, and making the space for URL shorter and breaking the URL onto two lines instead of the arrow.

@nguyetv what do you think should be done with this case where URL is exactly the max width of the button, forcing just the arrow onto next line?

**Comment by am9u** [comment]
FYI, I actually added an upadte for this earlier today (`white-space: nowrap`), but it hasn't landed in `master` yet.

**Comment by tobek** [comment]
Sweet

**Comment by am9u** [comment]
Addressed in: #1050
