### ISSUE TITLE
Visit Newsroom Button has broken character

### ISSUE THREAD

**Issue by myoung** [joincivil/Civil#1061]
![image](https://user-images.githubusercontent.com/187748/53895300-bd7ff200-3fff-11e9-8613-86f1f04a764b.png)

cc @picocassette

**Comment by nguyetv** [comment]
This button should be in the same style as the one on top 
![screen shot 2019-03-06 at 11 25 28 am](https://user-images.githubusercontent.com/6794566/53896727-95de5900-4002-11e9-948d-aee91c36dc76.png)

**Comment by am9u** [comment]
Fixed in #1064
