### ISSUE TITLE
Add "Welcome" modal after people transfer tokens

### ISSUE THREAD

**Issue by nguyetv** [joincivil/Civil#1124]
Users complaint that after they transfer their tokens, there's no message to tell them what to do next. 

Solution:
Short-term solution is to take people back to homework to read more stories or check out newsrooms on the Registry.

Design mock:

After clicking on this 'Confirm button”https://consensys.invisionapp.com/share/RAIZ3X2TVXM#/352073876_Transfer_Tokens_Confirm_01

This new modal screen shows up after people click on “Got it” from the previous screen (see screenshot)

https://consensys.invisionapp.com/d/main/#/console/14237549/352073875/preview

**Comment by am9u** [comment]
This ticket is superseded by #1186
