### ISSUE TITLE
Implement v1.1 of 'Review my vote' screen

### ISSUE THREAD

**Issue by nguyetv** [joincivil/Civil#1187]
Updated design: https://consensys.invisionapp.com/d/main/#/console/14237549/357402896/preview

The updated UI includes the following:
- New succinct intro copy
- one column layout with 'Add to calendar' button higher on the page
- a checkbox to remind users to save their info before Metamask can be activated. 
- Added a small transactions fee copy below Metamask button. 

confirm screen with "Add to Calendar" feature: https://consensys.invisionapp.com/d/main/#/console/14237549/347133791/preview

Current UI:
![Screen Shot 2019-04-08 at 8 03 53 AM](https://user-images.githubusercontent.com/6794566/55722744-119e3d80-59d5-11e9-884b-ec7c9e012af7.png)

**Comment by am9u** [comment]
@nguyetv FYI, we are currently using a open source package for the 'Add to My Calendar' button, so we don't have much ability to customize styling. I think typography and colors may be doable, but getting the icon in there might be tough.

If we really want an icon in there, we'd prob have to write our own component for Add To Calendar, which might extend this ticket for a few more days.

Also, can you confirm that the date format in the Invision mocks is the one we want? We talked last week about keeping the numeral format, as it was clearer for localization purposes, but if this has changed, please let me know.

**Comment by nguyetv** [comment]
@am9u Got ya. Don't worry about the icon then - it's not as important as the copy

And yes, the date format in the mockup is old. Please keep the current date formate. 

Thanks for checking :)
