### ISSUE TITLE
Allow Newsroom content to be loaded and saved from Github Gists

### ISSUE THREAD

**Issue by ritave** [joincivil/Civil#3]
Currently the only way to store and load content is through InMemoryProvider, an abstraction of ContentProvider, which destroys the content on website refresh. We need a more permanent way to store content in a way that allows easy debugging and editing.

Using Gists for this scenario is pretty cheeky and a functional and easy to maintain way to achieve this goal. A new implementation of a ContentProvider is needed.

**Comment by nickreynolds** [comment]
We don't need to support github gists anymore, we can just use IPFS which is what we might actually use in a real situation
