### ISSUE TITLE
Debug-UI has compiler errors when trying to use "fs"

### ISSUE THREAD

**Issue by nickreynolds** [joincivil/Civil#41]
- on branch `nickreynolds/tcr_wrapper` I made some changed to `debug-ui`, separating functionality into different pages
- When I try to use "fs" in any file in the `code` folder, I get the error `Module not found: Error: Can't resolve 'fs' in '/Users/nickreynolds/Civil/Civil/packages/debug-ui/src/code'` even though it has definitely been added, and that's reflected in `package.json`
- I think this has something to do with the `gulpfile`, but I'm not sure how to fix it

**Comment by ritave** [comment]
@nickreynolds is this still a problem?

**Comment by nickreynolds** [comment]
well kind of. The "propose and approve" button on a newsroom page in debug-ui previously relied on `fs` to read the file `assets/article.md` which doesn't seem to work. So while we don't necessarily have to use `fs` there should be some way to propose and approve content from the newsroom page.

**Comment by nickreynolds** [comment]
won't fix
