### ISSUE TITLE
Add Build Step to Keep Artifacts in Sync Between `core` and `contracts`

### ISSUE THREAD

**Issue by nickreynolds** [joincivil/Civil#43]
- right now, before generating `.ts` wrappers in `core`, the artifacts must be copied over manually from `contracts` package. When we migrate contracts via truffle, the artifacts in `core` become outdated, and don't contain correct per-network deployed addresses.
- modify build process so that artifacts are kept in sync between the 2 packages, so that when accessing deployed addresses via `core` we have the most recent deployed contracts.

**Comment by ritave** [comment]
Along with @walfly we've talked about a quick fix for this - have an additional artifacts folder (`debugArtifacts`) in core that are debug only and are automatically copied  from `@joincivil/contracts` during contract build and so one less step during development. They are not added to git and are only uses during local dev.

Publishing would still mean manually merging network from jsons into main artifacts folder

**Comment by nickreynolds** [comment]
done via `publish:artifacts`
