### ISSUE TITLE
Listing card in "Ready to Update" section not showing "ready to complete"

### ISSUE THREAD

**Issue by nickreynolds** [joincivil/Civil#470]
- Listing that had an appeal requested and not granted is ready to complete, but the listing card doesn't show that

<img width="1308" alt="screen shot 2018-09-25 at 10 17 08 am" src="https://user-images.githubusercontent.com/1156755/46020447-6ec34900-c0ac-11e8-97b5-29789f621419.png">

**Comment by am9u** [comment]
Addressed in #475
