### ISSUE TITLE
Listing Page Doesn't Update to Whitelisted Status after Updating Newsroom to be Approved

### ISSUE THREAD

**Issue by nickreynolds** [joincivil/Civil#505]
- after performing the updateStatus transaction on a newsroom that should be whitelisted, the page does not update properly once the transaction is confirmed, have to refresh page to get correct data

**Comment by am9u** [comment]
Right now the dapp waits for the whitelisted event to come in before updating the UI, which from personal observation, can be slow.

We should verify that this is actually a bug and not some slowness related to our event subscriptions/listeners.

Alternatively, we can explore either
1) optimistically updating Redux with the state we expect for the listing
2) requesting the listing / challenge status directly from the Crawer APIs

**Comment by nickreynolds** [comment]
in listingEvent.ts - `tcr.allEventsExceptWhitelistFromBlock` - I don't think we're doing anything to update Redux state when a whitelisted even comes through
