### ISSUE TITLE
Respond to MetaMask "Breaking Change: No Accounts Exposed by Default"

### ISSUE THREAD

**Issue by nickreynolds** [joincivil/Civil#523]
- https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8
- we should replace the user-balance section with a button/link that kicks off this enable flow

**Comment by nickreynolds** [comment]
- should also prompt user to install metamask if not found

**Comment by walfly** [comment]
Is there a design for the prompt?

**Comment by nickreynolds** [comment]
design incoming but could do an undesigned link in the meantime

**Comment by nickreynolds** [comment]
implemented but some bugs found related to this, will make tickets for them
