### ISSUE TITLE
Dashboard doesn't display challenges / listings properly when GraphQL is enabled

### ISSUE THREAD

**Issue by am9u** [joincivil/Civil#631]
My Activity/Dashboard needs to hydrate its views from GraphQL when it is enabled

**Comment by nickreynolds** [comment]
I actually don't think it needs to hydrate via GraphQL. Right now the graphql queries won't work for a user's historic actions. So we still use the web3 way of getting data for user info, there must just be some small issue preventing this from working correctly when graphql is selected.
