### ISSUE TITLE
Lag in Newsroom Listing Updating to "Under Challenge" After Challenge

### ISSUE THREAD

**Issue by myoung** [joincivil/Civil#721]
After challenging a newsroom and getting the “success!” modal, it took me back to the newsroom listing and said that it was approved, not “under challenge.” Assuming this is a caching/graphql bug. After refreshing the listing twice, I got the “under challenge” message.

https://dapp.staging.cvl.pub/listing/0x3486cb86dba1751f0f6f5adf78ec9f6e30edba14

**Comment by nickreynolds** [comment]
so I've confirmed that it does update eventually without having to refresh. I think some delay here is just what we're going to have to live with. There's delay at each step, not really much we can do, imo.
