### ISSUE TITLE
Error, Loading, Not Found views for DApp

### ISSUE THREAD

**Issue by am9u** [joincivil/Civil#760]
These aren't really 404/500 errors, since our server doesn't return those response, but we need to display the appropriate messaging when:

- GraphQL / Web3 is loading data
- GraphQL returns an error
- User hotlinks to a missing listing or URL not handled by `react-dom-router`

Proposal:
Display the octopus error icon with simple messaging

**Comment by nickreynolds** [comment]
for graphql errors it would be great if we include a button that says "click here to load via web3" and turns off the graphql toggle
