### ISSUE TITLE
Salt and Vote Option are inconsistently populating from localstorage when Revealing Votes

### ISSUE THREAD

**Issue by am9u** [joincivil/Civil#780]
A possible source of this issue could be a race condition, where we try loading the data from localstorage in the constructor of the Reveal Vote component, but the localstorage key needs the user's EthAddress, which may be loaded after the component is initialized. If this is the case, we should move the getting of vote data from localstorage into the `render` method of the component.

**Comment by nickreynolds** [comment]
downgraded priority on this because i'm pretty sure it only affects us devs because we use the same dapp with different instances of contracts deployed and switch between staging and local front-end a lot (salt may be saved on local front-end but are trying to reveal on staging)

**Comment by nickreynolds** [comment]
I think we're good to close it. It's basically not real, I think.
