### ISSUE TITLE
Appeal decision banner styles are not up-to-date

### ISSUE THREAD

**Issue by am9u** [joincivil/Civil#794]
![image](https://user-images.githubusercontent.com/143426/51402676-1e20a180-1b1c-11e9-8b89-34e10553d79b.png)

They should match this mock:
https://consensys.invisionapp.com/share/RAIZ3X2TVXM#/314525192_04_Registry_-_Appeal_To_Council

**Comment by nickreynolds** [comment]
we don't want the challenge results here as well?
