### ISSUE TITLE
When GraphQL is enabled, listing w/ successful Appeal Challenge shows as still "Under Challenge" after the appeal challenged is resolved

### ISSUE THREAD

**Issue by am9u** [joincivil/Civil#818]
GraphQL enabled:
![image](https://user-images.githubusercontent.com/143426/51756988-4b2b0200-2090-11e9-9bcb-56ddd250c297.png)

GraphQL disabled:
![image](https://user-images.githubusercontent.com/143426/51757035-6433b300-2090-11e9-9896-bbfdd39de207.png)

GraphQL response:
![image](https://user-images.githubusercontent.com/143426/51757277-f6d45200-2090-11e9-97c1-fa8af652ae65.png)

- The crawler doesn't appear to clear out the `challenge` field after an Appeal Challenge has been resolved

**Comment by nickreynolds** [comment]
believe this isn't happening anymore
