### ISSUE TITLE
Build Badge should only reflect status of last master build

### ISSUE THREAD

**Issue by nickreynolds** [joincivil/Civil#85]
- Right now, if a branch is pushed that breaks something (or has no tests, such as the gh-pages branch), the badge shown in the README of the root of monorepo shows an error.
- The badge should only reflect the status of the last master build, not any branch

**Comment by ojshaw** [comment]
I could do this if it hasn't been resolved yet.

**Comment by nickreynolds** [comment]
this issue might not be happening anymore, seems like build badge is only showing result of master builds now.

**Comment by ojshaw** [comment]
cool. I'll look into something else then :P
