### ISSUE TITLE
Implement "wrong network" banner warning for Dapp

### ISSUE THREAD

**Issue by am9u** [joincivil/Civil#891]
Based on the environment, the dapp should display a warning if the user is not on the corresponding network, ie:

If the user is in Production, they should see a message saying "You are not on Mainnet"

If the user is on Staging, the message should say "You are not on Rinkeby"

**Comment by nickreynolds** [comment]
I'm not sure this is really necessary. We have the dialog that pops up if user is on wrong network. Suppose it'd be nice to have a little message if connected to mainnet when on staging, but it should be hard to do anything of importance by accident (especially if your mainnet tokens are controlled by a hardware wallet)
