### ISSUE TITLE
Use paginating versions of the GraphQL queries

### ISSUE THREAD

**Issue by petersng** [joincivil/Civil#897]
The Dapp is currently on the legacy non-paginating versions of the GraphQL queries.  Should switch over to the paginating versions which are all prefixed with `tcr` in the schema as the non-paginating versions return limited number of results.

The pagination follow relay-style cursor pagination https://www.apollographql.com/docs/react/features/pagination.html#relay-cursors

**Comment by nickreynolds** [comment]
what is the current limit on how many results will be returned by a query?

**Comment by petersng** [comment]
By default, it is 25 per request.  If you set the `first` param in the GraphQL query, that is basically the number of items to try and retrieve.  I don't believe we limit it yet, but will add something to limit soon.  Pagination is ideal once the number of newsrooms, events, etc. get large, but if you need an interim solution, we can set that `first` count higher than 25, say 100.

**Comment by petersng** [comment]
Also, that default is not set in stone, so we can play with this value and play around with the max items returned.

**Comment by nickreynolds** [comment]
yeah we should bump it to 100 for the time being, since that should cover us for a while. but using paginated versions should definitely be #1 post-launch priority

**Comment by petersng** [comment]
ok, do you want to do count increase in the GraphQL query?  If we do it that way, the Dapp retains control over it.
