### ISSUE TITLE
New Application status shows duplicate tooltips, one with NaN days

### ISSUE THREAD

**Issue by tobek** [joincivil/Civil#905]
"Waiting for Approval" tooltip:
​
![image 1](https://user-images.githubusercontent.com/3081073/52808365-b185bd80-305b-11e9-8eac-07a04cc758f4.png)

Right above it, the "New Application" tooltip:

![image](https://user-images.githubusercontent.com/3081073/52808376-bb0f2580-305b-11e9-8bd3-660677809f93.png)

Visible e.g. on mainnet application https://registry.civil.co/listing/0xb27bebdb4817960824c523483e8981b25631a6d5

**Comment by nickreynolds** [comment]
someone (probably Jon) fixed this
