### ISSUE TITLE
Approved Date Not Showing on Listing Page

### ISSUE THREAD

**Issue by myoung** [joincivil/Civil#948]
Viewing the Cannabis Wire listing in Chrome, no MM installed. Listing on the left (chrome, no MM) shows all of the listing info but the Approved Date is missing. Listing on the right (chrome, no MM, incognito) shows the Approved Date.

https://registry.civil.co/listing/0x954d3a15c27e65f70504a6c4f0ebad79cce5fa11

![image](https://user-images.githubusercontent.com/187748/53113637-0d46bf80-3510-11e9-864c-74eaff6fe84f.png)

**Comment by nickreynolds** [comment]
fixed

**Comment by myoung** [comment]
looks good on staging! let me know when it's on production - i'm happy to take another look.
